### ISSUE TITLE
🎨[STYLE CHANGE] : Create basic necessary Design

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/ARrow#10]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Create all the basic necessary Designs.
Like Login / signup , get started etc
Use Figma.

### Reason for Change:

NA

### Current Styling:

NA

### Proposed Styling:

NA

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/06660b52-5d19-476c-90f9-e4af77d0bf92)
Current Styling.
Waiting for Final Workflow diagram To create New pages accordingly

**Comment by Siddhant-Patil0203** [comment]
Nice job, @LadeHarshal ! 👏   Your design looks great. At this point, I don't think we need a light version, so let's proceed with the dark mode. I'll work on creating a workflow diagram as soon as possible, and in the meantime, you can work on creating an onboarding screen. Here are some images for your reference :

![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/7fc0237e-f47f-4056-9f16-014fd23386ef)
![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/0e678201-7564-4f11-8d84-996408964988)
![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/fb341b48-5f92-456d-8694-f7d54cc89d79)

**Comment by Siddhant-Patil0203** [comment]
Hey @LadeHarshal, 

Could you please start designing the my profile page for different types of users such as Students, Faculties, Staff, Visitors, and Admins? Also, please create a page that asks the user about their status (student, faculty, etc.) and then directs them to the appropriate page. For instance, if the user selects "student," they should then be asked about their year of study, branch, interests, etc.

Please create a separate issue for this.
Distinct issues for Profile Page and for KYC,
So that it will be easier for us to manage.

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Please consider adding the Figma link to the Readme file and create a folder named "logo" in the assets directory. This folder should contain high-definition logos of Arrow. You may create an issue for this task.Also add the Figma link on Readme and a logo folder in assest containing the HD logos of ARrow, you can make the issue for this.

**Comment by LadeHarshal** [comment]
> @LadeHarshal Please consider adding the Figma link to the Readme file and create a folder named "logo" in the assets directory. This folder should contain high-definition logos of Arrow. You may create an issue for this task.Also add the Figma link on Readme and a logo folder in assest containing the HD logos of ARrow, you can make the issue for this.

This has been done and i have created a pull request for the same.
