### ISSUE TITLE
✨[Feature] : Add specific location points to place 3d models 

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/ARrow#11]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/8347400a-bc02-435c-9c33-49e9b83a7f13)

Add location pointer, where we will be having the 3D model.

### Add Screenshots

NA

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Saurabb-coder** [comment]
> Model
1.  Namaste Model at College Gate in Indian Tradition
2.  2 Player playing at cricket ground {Batting and Bowling}
3.  Fountain animation at front of Gym

> All 5Dept, libs, students section, hostel, mess, gym
     Animation of each section would contain a 3D animation followed by the section's name.
     eg: A laptop (animation) followed by Computer Science and Engineering(name) -- Banner Kind off

> Hods, Principal name animation along with their profile photo

**Comment by vishal10kesharwani** [comment]
> @Saurabb-coder 
> - I Liked the First Idea 
> - Discuss with @vishal10kesharwani the 2nd point, that will it be possible for us to do. 
> - 3rd Idea is also nice 
> - Rest General banner is also good, 
> 
> See if we can add anything to the main building's open space, where there is badminton next.
> Also, check if we can add anything in the Civil Meuseam place 
> and in the place between the main building and boys' hostel where there is circular thing 

with reference to 2nd point , i think we could add sfoorti sports video links uploaded on YouTube for reducing the load time of app .

**Comment by vishal10kesharwani** [comment]
> > @Saurabb-coder 
> > - I Liked the First Idea 
> > - Discuss with @vishal10kesharwani the 2nd point, that will it be possible for us to do. 
> > - 3rd Idea is also nice 
> > - Rest General banner is also good, 
> > 
> > See if we can add anything to the main building's open space, where there is badminton next.
> > Also, check if we can add anything in the Civil Meuseam place 
> > and in the place between the main building and boys' hostel where there is circular thing 
> 
> with reference to 2nd point , i think we could add sfoorti sports video links uploaded on YouTube for reducing the load time of app . 

It's not a difficult task by the way to create a cricket model, but it will take a lot of load.

**Comment by Siddhant-Patil0203** [comment]
> It's not a difficult task by the way to create a cricket model, but it will take a lot of load.

Okay, do it at the end, if we have the time @vishal10kesharwani
