### ISSUE TITLE
Feat: Blog Post

### ISSUE THREAD

**Issue by mayankgongal5** [UBA-GCOEN/ARrow#114]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

[ARrowBlog1.odt](https://github.com/UBA-GCOEN/ARrow/files/12909136/ARrowBlog1.odt)

### Add Screenshots

[ARrowBlog1.odt](https://github.com/UBA-GCOEN/ARrow/files/12909138/ARrowBlog1.odt)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@mayankgongal5 Pls. Work with this [Doc](https://docs.google.com/document/d/1fvDWkm6pOfs8a0IxTKnMqoJKoqbjfIZYiiW_kDSd1VU/edit?usp=sharing), send the request I will approve it and changes will be told there :)

**Comment by Siddhant-Patil0203** [comment]
@mayankgongal5 add an index navigator at the start

**Comment by mayankgongal5** [comment]
I dont have access to that Doc file
