### ISSUE TITLE
Creating a welcome/getStarted page

### ISSUE THREAD

**Issue by LadeHarshal** [UBA-GCOEN/ARrow#32]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

This will we made to highlight the app features, as well as introduce the user  how he can navigate with the app and use its features.

### Reason for Change:

Every app has its series of welcom/get started section

### Current Styling:

Single page is present

### Proposed Styling:

Multiple pages with sliding action that wil alternate between these pages

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
The prev and next buttons are not looking good, try keeping just arrows for them or try something new

**Comment by LadeHarshal** [comment]
> @LadeHarshal The prev and next buttons are not looking good, try keeping just arrows for them or try something new

Will do.

**Comment by LadeHarshal** [comment]
Actually the darker background ones look better.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/bcb86c04-e6cb-4ac7-b61a-0b0a22e07c1d)

**Comment by Siddhant-Patil0203** [comment]
> Actually the darker background ones look better. 

Yup @LadeHarshal We will go ahead with the third one

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal add a skip button for the ones who are returning users

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/b7ac37ba-44f4-4067-a92a-600fc9386651)
Okay then should we consider this as our final piece?

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/5639cb18-0084-4a62-9816-79e3e79b7403)
Clearer image

**Comment by Siddhant-Patil0203** [comment]
We will be having a short meet on this @LadeHarshal

**Comment by LadeHarshal** [comment]
Planning to keep these pages.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/b7312a84-b003-4338-863a-653227305747)

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Comment by Siddhant-Patil0203** [comment]
Discuss in the meet, 
just pin me here when the changes told is done

**Comment by Siddhant-Patil0203** [comment]
This Issue is completed Now
