### ISSUE TITLE
Feat: Home Page for the application

### ISSUE THREAD

**Issue by LadeHarshal** [UBA-GCOEN/ARrow#42]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

This will be the doorway to use all the features of our application

### Add Screenshots

![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/d42c23eb-853a-4ca9-bd19-c8d854cfd1a9)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Initially design is good, refine it as per our discussion

**Comment by LadeHarshal** [comment]
Will do

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
How is the designing going on ?
Please do it little bit faster, as we have show it in design phase

**Comment by LadeHarshal** [comment]
In progress.
Planning on going ahead with this one.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/2d0bec56-1868-424d-9ae5-67cdd85ef19d)

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/d4ac50e9-7a6c-4eea-be2e-14a7b3e6a54f)
As per todays meet.

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Beautiful Design 😍 

Just a few things 
![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/46244ad1-b5d4-487c-9ac3-b560ea7ccdd2)
try to change this section ⬆️ 
Also, Notification is a general button and not an option in the menu  : 
![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/0863cafb-7f9f-45e4-80e5-15179f0bd5a7)
there should be a navbar at the bottom or side where the users can access notifications their profiles etc.

or try adding notifications and profiles on the top right just like YouTube 

Rest the design is amazing, great job

**Comment by Siddhant-Patil0203** [comment]
Checkout this for inspiration : 
https://dribbble.com/shots/19389780-Electricity-Meter-Reader-User-App/attachments/14529165?mode=media

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/23c8ae0c-3239-4b7f-bce5-a684fa136195)
Made the required changes

**Comment by Siddhant-Patil0203** [comment]
Okay we will discuss about this in the meet @LadeHarshal

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/81dc9e02-069b-4624-ab95-a031d5654e4d)

**Comment by LadeHarshal** [comment]
This is how the location page Looks.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/8c211730-c83f-4295-b993-12b206e2f054)
and this is Events page.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/26df109e-7c91-48ba-9ca8-bf2380dead65)

**Comment by Siddhant-Patil0203** [comment]
Great work, @LadeHarshal! Please consider adding this to the final page in Figma.
