### ISSUE TITLE
Feat:Profile page and KYC pages

### ISSUE THREAD

**Issue by LadeHarshal** [UBA-GCOEN/ARrow#43]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Includes the selection of user type as well as edit my profile page and KYC page.

### Add Screenshots

![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/634ffe72-c4a0-434d-bc0a-7a1e89db9963)
This is the first part i.e the selection of user type.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Initially design is good, refine it as per our discussion

**Comment by LadeHarshal** [comment]
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/9d9fc7f2-2d3f-4011-a132-470b39d2ac6e)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/474b1e93-7dc5-4d10-bb7f-10af77508c99)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/dcdb2a5d-5045-47af-959d-fd1953e9cd72)
The current designs of the pages

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Discuss in the meeting, 
Just pin me here when the changes are done 

The design should be similar to Upwork onboarding questions
Few Designs for inspiration : 
![WhatsApp Image 2023-09-05 at 19 49 52](https://github.com/UBA-GCOEN/ARrow/assets/77800620/d81135b4-fc95-41d7-82f5-9b610342abb1)
![WhatsApp Image 2023-09-05 at 19 55 12](https://github.com/UBA-GCOEN/ARrow/assets/77800620/72ddee94-67ff-4366-ae6e-86bb18271379)
![WhatsApp Image 2023-09-05 at 20 06 35](https://github.com/UBA-GCOEN/ARrow/assets/77800620/36a38f42-eaaa-4a50-904e-29d0c690eb46)
![WhatsApp Image 2023-09-05 at 20 07 02](https://github.com/UBA-GCOEN/ARrow/assets/77800620/31d18fa2-0914-4272-857c-d1320833dc14)

**Comment by LadeHarshal** [comment]
Done with the initial part for faculty.
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/715321ea-ae22-4a93-bfcd-3c60cf43b2e4)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/f10d0e6b-82ac-4140-8dbf-10433ffec250)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/6f2dbddc-7bde-4a65-ac4a-ef2a6afa20a2)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/f7d450d2-2927-47ba-9919-062805fda6e4)
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/a5b11ecd-c028-4a5b-9f7f-3f9c48ce940f)

**Comment by LadeHarshal** [comment]
@Siddhant-Patil0203

**Comment by Siddhant-Patil0203** [comment]
We will discuss this in the meet

**Comment by LadeHarshal** [comment]
Profile Page
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/7257f3a0-0780-457d-a834-2ac2929d1661)
For Onboarding
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/f28145a5-dfcf-433b-9db5-351cbb23f458)
The above pages will be common.
For Faculty
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/92771bf7-97e3-40e3-aa2b-17599e3526f2)
For Students
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/60703c07-5c84-4a0b-9bbc-f6f604831f75)
For Staff
![image](https://github.com/UBA-GCOEN/ARrow/assets/92210851/4d8e98d7-340d-4497-ba1c-2822f44e6e7a)
These pages will follow the common pages.

**Comment by Siddhant-Patil0203** [comment]
Great Work @LadeHarshal !! 🚀
Please add them in the final page of fimga
