### ISSUE TITLE
[STYLE CHANGE] Design profile page according to the user 

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/ARrow#45]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Please design "your profile" according to the user specifications.
Please refer the flowchart for the user specifications.

### Reason for Change:

NA

### Current Styling:

NA

### Proposed Styling:

NA

### Screenshots or Design Mockups (optional):

NA

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal please go ahead with this

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal Please Acknowledge this

**Comment by LadeHarshal** [comment]
On it
